### ISSUE TITLE
Agreements about license changes

### ISSUE THREAD

**Issue by XZhouQD** [XZhouQD/boxnote-converter#3]
G'day @aitalian ,

I'm planning to make this project licensed under MIT instead of AGPLv3 to provide less limitations on using it. To ensure this goes through a right way of changing opensource license, I'm asking if you agree or have other suggestions/concerns on this as you are contributor of the project as well.
I'll keep this open and will not change the license until receiving agrees from you or proceeding license change after 30 June 2023 if no response.

Regards,
XZhouQD

**Comment by aitalian** [comment]
Sounds good, I agree 👍 Thank you!
